language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true

install: travis_retry composer install --no-interaction --prefer-source --dev
script: phpunit

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
